### ISSUE TITLE
Post-Publishing tasks

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-liberty-deep-dive-gradle#6]
Post-Publishing Tests (Unice)
 ---
 
 - [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
 - [ ] ~~Clone repo and test finish directory with no error~~
 - [x] test the start directory end-to-end
 
 Other post-publishing tasks (to be done by the Admin Team)
 ---
 - [x] Add description for the repo with link to the guide published URL
 - [x] Double check the SEO title and description are added for the guide
 - [x] Create the Home and Branches wiki pages
 - [x] Ensure automated test for PR and Continuous Tests are enabled for both `prod` and `staging` branches and are run by Github action, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides)
    - make sure test.yml has no draft and linter default branch is prod
 - [x] make sure that test.yml is updated
 - [x] Ensure the automated tests are running successfully for the daily builds
  - [ ] ~~remove `draft-guide-x` from guides-common/.github/workflows/drafts-to-test.json~~
 - [ ] ~~Ensure the automated tests are running successfully for the daily docker image, if the guide uses a docker image~~
 - [ ] ~~Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/websphere/openliberty-guides-team/wiki/Subscribe-static-guide-repository-to-a-slack-channel)~~
 - [x] Enable `prod` and `staging` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides)
    -  make sure the Branch protection rules were created
 - [x] Create github action `.github/workflows/add-to-projects.yml`
    - https://github.com/OpenLiberty/guides-common/blob/prod/.github/workflows/add-to-projects.yml
 - [x] Clean up branches, issues, and PRs
 - [ ] ~~create blog issue~~
    - ~~visit https://github.com/OpenLiberty/open-liberty/issues/new/choose and select `Open Liberty GA release blog post`~~
    - ~~issue link~~
 - [ ] ~~Send announcement to slack channels~~
    - ~~dev_advocates_java~~
    - ~~was-lib-guides-dev~~
    - ~~was-gm-testing~~
 - [x] enable analytic
    - `Open Liberty - Guides - Individual Guide Clones` and `Individual Guides Referrals` dashboards
 - [ ] ~~Arrange a demo at the EOI meeting~~

**Comment by mbuamuh** [comment]
###  Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io

- [ ] https://openliberty.io/guides/liberty-deep-dive-gradle.html#documenting-apis: 
       - Specify in which directories the server.xml and build.gradle files are
- [ ] https://openliberty.io/guides/liberty-deep-dive-gradle.html#enabling-configurable-ports-and-context-root: See **`Replace the build.gradle file`**. 
       - liberty.server.var.'default.http.port': value is 9081 in document, meanwhile the code on the right in build.gradle is 9080
       - liberty.server.var.'default.https.port': value is 9445 in document, meanwhile the code on the right in build.gradle is 9443
       - liberty.server.var.'default.context.root': value is trial in document, meanwhile the code on the right in build.gradle is liberty

**Comment by mbuamuh** [comment]
###  test the start directory end-to-end
- [x] https://openliberty.io/guides/liberty-deep-dive-gradle.html#enabling-configurable-ports-and-context-root: The URLs http://localhost:9081/trial/api/systems and http://localhost:9081/openapi/ui/ do not work. This is due to wrong port numbers and context root in the build.gradle file, in his section.
- [x] https://openliberty.io/guides/liberty-deep-dive-gradle.html#providing-metrics: 
   - https://localhost:9443/metrics/application returns an empty screen, which is not what is expected as per the documentation

**Comment by gkwan-ibm** [comment]
@mbuamuh 
> https://openliberty.io/guides/liberty-deep-dive-gradle.html#enabling-configurable-ports-and-context-root: The URLs http://localhost:9081/trial/api/systems and http://localhost:9081/openapi/ui/ do not work. This is due to wrong port numbers and context root in the build.gradle file, in his section.
- did you update the `liberty.server.var...` variables in the build.gradle?

@gkwan-ibm 
That works fine when i update the variables in the build.gradle. But the issue is when one clicks on the variable on the left side of the screen, the highlighted variable on the right side still shows the old values. For example instead of:

```
ext  {
    liberty.server.var.'default.http.port' = '9081'
    liberty.server.var.'default.https.port' = '9445'
    liberty.server.var.'default.context.root' = '/trial'
}
```
one sees:
```
ext  {
    liberty.server.var.'default.http.port' = '9080'
    liberty.server.var.'default.https.port' = '9443'
    liberty.server.var.'default.context.root' = '/inventory'
}
```

**Comment by gkwan-ibm** [comment]
@mbuamuh 
>  https://openliberty.io/guides/liberty-deep-dive-gradle.html#providing-metrics:
>  - https://localhost:9443/metrics/application returns an empty screen, which is not what is expected as per the documentation


- did you point your browser to the http://localhost:9080/openapi/ui URL to try out your application and call some of the endpoints?
@gkwan-ibm This works alright, with browsing the application first

**Comment by gkwan-ibm** [comment]
close
- all tasks were completed
